# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [2]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt
pip install numpy --upgrade

SyntaxError: invalid syntax (1550180525.py, line 2)

### 2. Install/Upgrade another package (e.g. Pandas) 

In [1]:
pip install pandas --upgrade

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   -----------------

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\http\client.py", line 473, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\GENIUS ELECTRONICS\anaconda3\Lib\soc

### 3. Import NumPy as <i> np </i>

In [ ]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [6]:
import numpy as np
array_hw_1=np.array([[4,5,7,10]])


### 5. Display the new array on screen

In [5]:
array_hw_1

array([[ 4,  5,  7, 10]])

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [7]:
import numpy as np
array_hw_1=np.array([[4,5,7,10],[4,5,7,10]])
array_hw_1

array([[ 4,  5,  7, 10],
       [ 4,  5,  7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [11]:
import numpy as np
array_hw_1=np.array([[4,5,7,10],[4,5,7,10]])

mean = np.mean(array_hw_1)
mean

6.5

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [38]:
import numpy as np
array_hw_1=np.array([[4,5,7,10],[7,6,9,9]])
a= np.mean(array_hw_1,axis=1)
a

array([6.5 , 7.75])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [39]:
import numpy as np
array_hw_1=np.array([[4,5,7,10],[7,6,9,9]])
a= np.mean(array_hw_1,axis=0)
a

array([5.5, 5.5, 8. , 9.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [9]:
import numpy as np
array_hw_1=np.array([[4,5,7,10],[7,6,9,9]])
a= np.mean(array_hw_1,axis = 0,dtype=int)
a


array([5, 5, 8, 9])