<hr style="border:5px solid #108999"> </hr>

# pandas Series <hr style="border:4.5px solid #108999"> </hr>

## pandas Series: .unique() & .nunique()

In [1]:
import pandas as pd

In [12]:
data = pd.read_csv('Location.csv')

location_data = data.copy()

location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [13]:
type(location_data)

pandas.core.frame.DataFrame

In [14]:
location_data.describe()

Location
count          1043
unique          296
top     Location 25
freq             31

In [15]:
len(location_data)

1043

In [21]:
location_data.nunique()

Location    296
dtype: int64

In [22]:
type(location_data.nunique())

pandas.core.series.Series

In [23]:
location_data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [19]:
type(location_data.unique())

AttributeError: 'DataFrame' object has no attribute 'unique'

In [20]:
location_data.unique

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
type(location_data.unique)

## pandas Series: Converting Series into Arrays (.values, .array, .to_numpy())

In [24]:
import pandas as pd
import numpy as np

In [25]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B' : 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [26]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [27]:
type(prices_per_category.values)

numpy.ndarray

In [28]:
prices_per_category.array

<NumpyExtensionArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [29]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [30]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [31]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [32]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [33]:
type(test_array[0])

numpy.float64

In [34]:
prices_per_category.values[0]

22250

In [35]:
type(prices_per_category.values[0])

numpy.int64

In [36]:
prices_per_category.array[0]

22250

In [37]:
type(prices_per_category.array[0])

numpy.int64

In [38]:
prices_per_category.to_numpy()[0]

22250

In [39]:
type(prices_per_category.to_numpy()[0])

numpy.int64

## pandas Series: .sort_values()

In [1]:
import pandas as pd

In [2]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [3]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [4]:
numbers.sort_values(ascending=True)

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [5]:
numbers.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [41]:
data = pd.read_csv('Location.csv')
location_data = data.copy()
location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [7]:
location_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [8]:
location_data.sort_values(ascending=True)

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [9]:
location_data.sort_values(ascending=False)

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
          ...     
623    Location 10
716    Location 10
465     Location 1
884     Location 1
637     Location 1
Name: Location, Length: 1043, dtype: object

## Attribute and Method Chaining

In [42]:
import pandas as pd

In [44]:
data = pd.read_csv('Location.csv')
location_data = data.copy()
location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [12]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [13]:
location_data.name

'Location'

In [45]:
location_data.index.name

In [46]:
location_data.index.name = 'Index'

In [16]:
location_data

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [47]:
location_data.index.name

'Index'

In [48]:
location_data.sort_values()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [19]:
location_data.sort_values().head()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
Name: Location, dtype: object

In [20]:
location_data.sort_values().tail()

Index
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, dtype: object

In [21]:
location_data.index

RangeIndex(start=0, stop=1043, step=1, name='Index')

In [22]:
type(location_data.index)

pandas.core.indexes.range.RangeIndex

In [23]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)

## pandas Series: .sort_index() 

In [24]:
import pandas as pd

In [25]:
data = pd.read_csv('Location.csv', squeeze = True)
location_data = data.copy()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [26]:
location_data.sort_values(ascending=False)

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
          ...     
623    Location 10
716    Location 10
465     Location 1
884     Location 1
637     Location 1
Name: Location, Length: 1043, dtype: object

In [27]:
location_data_sv = location_data.sort_values(ascending=False)
location_data_sv.head()

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
Name: Location, dtype: object

In [28]:
location_data_sv.index

Int64Index([ 372,  757,  669,  128,  482,  271,   29,  612,  598,  518,
            ...
            1010,  329,  542,  298,   56,  623,  716,  465,  884,  637],
           dtype='int64', length=1043)

In [29]:
location_data_sv.index.sort_values()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
           dtype='int64', length=1043)

In [30]:
location_data_sv.head()

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
Name: Location, dtype: object

In [31]:
location_data_sv.index = location_data_sv.index.sort_values()

In [32]:
location_data_sv

0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [33]:
location_data_sv = location_data.sort_values(ascending=False)
location_data_sv.head()

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
Name: Location, dtype: object

In [34]:
location_data_sv.sort_index()

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [35]:
location_data_sv

372    Location 99
757    Location 98
669    Location 97
128    Location 97
482    Location 97
          ...     
623    Location 10
716    Location 10
465     Location 1
884     Location 1
637     Location 1
Name: Location, Length: 1043, dtype: object

In [36]:
location_data_sv = location_data_sv.sort_index(ascending=True)
location_data_sv

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object